version: '3.1'

services:
  rabbitmq1:
    container_name: rabbitmq1
    image: rabbitmq:management
    ports:
      - "15672:15672"
    volumes:
      - "./etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
      - "./etc/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie"
    environment:
      RABBITMQ_NODENAME: "cluster_A"
    networks:
      - rabbit_cluster_network

  rabbitmq2:
    container_name: rabbitmq2
    image: rabbitmq:management
    ports:
      - "15673:15672"
    volumes:
      - "./etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
      - "./etc/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie"
    environment:
      RABBITMQ_NODENAME: "cluster_b"
    networks:
      - rabbit_cluster_network

  rabbitmq3:
    container_name: rabbitmq3
    image: rabbitmq:management
    ports:
      - "15674:15672"
    volumes:
      - "./etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
      - "./etc/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie"
    environment:
      RABBITMQ_NODENAME: "cluster_c"
    networks:
      - rabbit_cluster_network

  haproxy:
    container_name: haproxy
    image: haproxy:lts-alpine
    ports:
      - "5672:5672"
      - "9005:9000"
    volumes:
      - "./etc/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
    networks:
      - rabbit_cluster_network

networks:
  rabbit_cluster_network:
